# Generated by Django 5.0.4 on 2024-04-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
