# Generated by Django 5.0.4 on 2024-04-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_cafe_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(default='5500000000000', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='whatsapp',
            field=models.CharField(default='5500000000000', max_length=15),
        ),
    ]
