# Generated by Django 5.0.3 on 2024-04-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_cliente_cafe_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='endereco',
            field=models.CharField(default='Endereço não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='cafe',
            name='foto_ambiente',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_cafeterias/'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='horas_funcionamento',
            field=models.CharField(default='Horário não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='cafe',
            name='link_redesocial',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='ticket_medio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, blank=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='descricao',
            field=models.TextField(default='Descrição não informada'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='nome',
            field=models.CharField(default='Nome não informado', max_length=100),
        ),
    ]
