# Generated by Django 5.0.3 on 2024-04-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_cafe_endereco_cafe_foto_ambiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='ticket_medio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
