# Generated by Django 5.0.3 on 2024-04-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_cadastrar_usuario'),
        ('apps', '0005_alter_cafe_ticket_medio'),
    ]

    operations = [
    ]
