# Generated by Django 5.0.4 on 2024-04-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_usercliente_remove_cadastrar_usuario_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercliente',
            name='cpf',
        ),
        migrations.AddField(
            model_name='usercliente',
            name='senha',
            field=models.CharField(default='00000000000000', max_length=200),
        ),
    ]
