# Generated by Django 5.0.3 on 2024-04-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_usercliente_remove_cadastrar_usuario_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercliente',
            options={},
        ),
    ]
