# Generated by Django 5.0.3 on 2024-04-23 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_usercliente_cpf_usercliente_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercliente',
            name='senha',
        ),
        migrations.AddField(
            model_name='usercliente',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve ter 11 dígitos, somente números')]),
        ),
        migrations.AlterField(
            model_name='usercliente',
            name='whatsapp',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Número de WhatsApp inválido')]),
        ),
    ]
