# Generated by Django 5.0.3 on 2024-04-24 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_usercliente_cpf_usercliente_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='ticket_medio',
        ),
    ]
