# Generated by Django 5.0.4 on 2024-04-24 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_cafe_ticket_medio'),
        ('apps', '0009_remove_usercliente_senha_usercliente_cpf_and_more'),
    ]

    operations = [
    ]
