# Generated by Django 5.0.3 on 2024-04-24 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_merge_20240423_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercliente',
            name='whatsapp',
        ),
    ]
