# Generated by Django 5.0.3 on 2024-04-24 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_remove_usercliente_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercliente',
            options={},
        ),
    ]
