# Generated by Django 5.0.3 on 2024-04-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_usercliente_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercliente',
            name='user',
        ),
    ]
