# Generated by Django 5.0.3 on 2024-04-24 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_remove_usercliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercliente',
            name='nome',
        ),
        migrations.AddField(
            model_name='usercliente',
            name='nome_completo',
            field=models.CharField(default='Desconhecido', max_length=150),
        ),
        migrations.AddField(
            model_name='usercliente',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercliente',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercliente',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve ter 11 dígitos.')]),
        ),
    ]
