# Generated by Django 5.0.3 on 2024-04-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_remove_usercliente_nome_usercliente_nome_completo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='nome',
            new_name='nome_cafeteria',
        ),
    ]
