# Generated by Django 5.0.3 on 2024-04-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_remove_usercliente_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercliente',
            name='username',
        ),
    ]
