# Generated by Django 5.0.3 on 2024-04-24 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_remove_usercliente_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercliente',
            name='confirm_password',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve ter 11 dígitos, somente números')]),
        ),
    ]
