# Generated by Django 5.0.3 on 2024-04-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_remove_usercliente_cpf'),
        ('apps', '0016_cafe_cnpj_cafe_responsavel_cafe_senha_and_more'),
    ]

    operations = [
    ]
