# Generated by Django 5.0.4 on 2024-04-24 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_merge_20240424_1645'),
        ('apps', '0018_alter_usercliente_confirm_password'),
    ]

    operations = [
    ]
