# Generated by Django 5.0.3 on 2024-04-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_merge_20240424_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercliente',
            old_name='nome_completo',
            new_name='username',
        ),
    ]
