# Generated by Django 5.0.4 on 2024-04-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_merge_20240424_2025'),
        ('apps', '0019_merge_20240424_2036'),
    ]

    operations = [
    ]
