# Generated by Django 5.0.3 on 2024-04-25 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_rename_nome_completo_usercliente_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercliente',
            old_name='username',
            new_name='nome_completo',
        ),
    ]
