# Generated by Django 5.0.4 on 2024-04-25 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_merge_20240424_2044'),
        ('apps', '0020_merge_20240424_2058'),
    ]

    operations = [
    ]
