# Generated by Django 5.0.4 on 2024-04-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_merge_20240424_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='whatsapp',
            field=models.CharField(default='5500000000000', max_length=11),
        ),
    ]