# Generated by Django 5.0.4 on 2024-04-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_rename_username_usercliente_nome_completo'),
        ('apps', '0022_alter_cafe_whatsapp'),
    ]

    operations = [
    ]
