# Generated by Django 5.0.4 on 2024-04-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_merge_20240425_0027'),
        ('apps', '0023_merge_20240425_0031'),
    ]

    operations = [
    ]
