# Generated by Django 5.0.3 on 2024-04-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_merge_20240424_1844'),
        ('apps', '0024_merge_20240425_0033'),
    ]

    operations = [
    ]
