# Generated by Django 5.0.3 on 2024-04-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_merge_20240425_1028'),
        ('apps', '0026_usercliente'),
    ]

    operations = [
    ]
