# Generated by Django 5.0.3 on 2024-05-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_alter_cafe_whatsapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCliente',
        ),
    ]
