# Generated by Django 5.0.3 on 2024-05-15 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_delete_usercliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(default='Desconhecido', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('confirm_password', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('horario_reserva', models.TimeField()),
                ('numero_de_pessoas', models.PositiveIntegerField(default=1)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.cafe')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.usercliente')),
            ],
        ),
    ]
