# Generated by Django 5.0.4 on 2024-05-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_usercliente_reservacafe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='senha',
        ),
    ]
