# Generated by Django 5.0.4 on 2024-05-17 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_remove_cafe_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='empresario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafeterias', to='apps.usercliente'),
        ),
    ]
