# Generated by Django 5.0.4 on 2024-05-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_usercliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercliente',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
