# Generated by Django 5.0.3 on 2024-05-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacafe',
            name='observação',
            field=models.TextField(default='Descrição não informada'),
        ),
    ]
