# Generated by Django 5.0.3 on 2024-05-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_reservacafe_observação'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacafe',
            old_name='observação',
            new_name='observacao',
        ),
    ]
