# Generated by Django 5.0.3 on 2024-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_rename_observação_reservacafe_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacafe',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
