# Generated by Django 5.0.4 on 2024-05-21 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_reservacafe_nome_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('valor_gasto', models.CharField(blank=True, max_length=50, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cafe')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.usercliente')),
            ],
        ),
    ]
