# Generated by Django 5.0.4 on 2024-05-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
