# Generated by Django 5.0.4 on 2024-05-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_alter_cafe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercliente',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
