# Generated by Django 5.0.3 on 2024-05-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_alter_cafe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='foto_experiencia',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_experiencias/'),
        ),
    ]
