# Generated by Django 5.0.3 on 2024-05-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_avaliacao_foto_experiencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='foto_experiencia',
            new_name='foto_avaliacao',
        ),
    ]
