# Generated by Django 5.0.3 on 2024-05-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_usercliente_profile_image'),
        ('apps', '0042_rename_foto_experiencia_avaliacao_foto_avaliacao'),
    ]

    operations = [
    ]
