# Generated by Django 5.0.3 on 2024-05-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0043_merge_20240522_0812'),
        ('apps', '0043_merge_20240522_0924'),
    ]

    operations = [
    ]
