# Generated by Django 5.0.3 on 2024-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0045_alter_usercliente_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacafe',
            name='numero_de_pessoas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
